fix spectrum color null as zero
flant/grafana-statusmap pull request #205
Opened 2021-05-31 16:10 UTC by badhop

#### Overview

#### What this PR does / why we need it

#### Special notes for your reviewer

#### Does this PR introduce a user-facing change?

```release-note

```

2021-06-03 07:47 UTC, nabokihms approved these changes
LGTM!

2021-06-03 08:22 UTC, diafour requested changes

2021-06-03 08:22 UTC, diafour commented on src/rendering.ts
> +      } else if (this.panel.color.mode === 'discrete') {
Hello! Thank you for your contribution!
I've run a plugin with the suggested change and it not work. Check for null is not working, because `bucket.value` may be "undefined". I've changed your code a bit and it works. Can you apply this suggestion?

```suggestion
      if (!bucket.value && this.panel.nullPointMode === 'as zero') {
        // bucket.value === 0 falls here, but it is fine.
        return this.colorScale(0);
      }
      return this.colorScale(bucket.value);
    } else if (this.panel.color.mode === 'discrete') {
```

2021-07-19 18:17 UTC, diafour commented
Thank you @badhop , I've pushed your commit as a part of #209 .

2021-07-19 18:17 UTC, closed without merging